# Testing XGB on well log datasets 

In [1]:
import numpy as np
from coremdlr.datasets import WellLoader, FaciesDataset
from coremdlr.models import FeaturePredictor, LambdaModel

Using TensorFlow backend.


### Picking your training and testing wells

In [2]:
fdset = FaciesDataset(["205-21b-3", "204-20-6a","204-24a-6","204-20-1Z"],
                    test_wells=["204-19-6"],
                    features=["logs"],
                    label_resolution=32*2, # 32 pixels ~ .5cm
                    logs_args={'scaler_kind': 'standard'})

In [3]:
fdset.load_or_generate_data()

Loading Well:  205-21b-3  from  /home/administrator/Dropbox/core_data/facies/train_data


Header section Parameter regexp=~P was not found.


Adding NaN log:  SP
Adding NaN log:  DTS
Feature shapes:  [('depth', (1920,)), ('top', (1920,)), ('base', (1920,)), ('logs', (1920, 11))]
Loading Well:  204-20-6a  from  /home/administrator/Dropbox/core_data/facies/train_data


Header section Parameter regexp=~P was not found.


Adding NaN log:  SP
Adding NaN log:  DTS1
Adding NaN log:  DTS2


ValueError: b'os' is not in list

In [4]:
import hyperopt
from hyperopt import hp
from hyperopt.pyll.base import scope
from sklearn.metrics import f1_score, log_loss
from sklearn.utils.class_weight import compute_sample_weight

# for balanced log_loss computation
sample_weights = compute_sample_weight('balanced', fdset.y_test) 

fmodel_args = {
    'logs': {
        'model': 'LambdaModel',
        'model_args': {'feature': 'logs'}
    }
}

XGB_SEARCH_SPACE = {
    'model_type' : 'XGB',
    'max_depth' : scope.int(hp.quniform('max_depth', 3, 10, 1)),
    'learning_rate' : hp.uniform('learning_rate', 0.01, 0.2),
    'n_estimators' : scope.int(hp.quniform('n_estimators', 10, 1000, 1)),
    'objective' : 'multi:softprob',
    'n_jobs' : 2,
    'gamma' : hp.uniform('gamma', 0, 0.5),
    'subsample' : hp.uniform('subsample', 0.3, 1),
    'colsample_bytree' : hp.uniform('colsample_bytree', 0.3, 1.0),
    'colsample_bylevel' : 1,
    'reg_alpha' : 0,                                    # L1 penalty
    'reg_lambda' : hp.uniform('reg_lambda', 0.1, 10),   # L2 penalty
    'tree_method' : 'gpu_exact',
}

def train_xgb_model(model_config):
    xgb_predictor = FeaturePredictor(fdset, model_args=model_config, feature_model_args=fmodel_args)
    test_acc = xgb_predictor.fit(fdset, verbose=False)
    y_pred = xgb_predictor.predict(fdset.X_test)
    print('F1 score:', f1_score(fdset.y_test, y_pred, average='macro'))
    return log_loss(fdset.y_test, xgb_predictor.predict_proba(fdset.X_test), sample_weight=sample_weights)

In [5]:
best_params = hyperopt.fmin(
    fn=train_xgb_model,
    space=XGB_SEARCH_SPACE,
    algo=hyperopt.rand.suggest,
    max_evals=50
)

Training model for feature:  logs
F1 score: 0.19325485051610644
Training model for feature:  logs
F1 score: 0.12080616546360314
Training model for feature:  logs
F1 score: 0.17436836501990682
Training model for feature:  logs
F1 score: 0.2046141582605648
Training model for feature:  logs
F1 score: 0.16248938083347025
Training model for feature:  logs
F1 score: 0.18545532128887673
Training model for feature:  logs
F1 score: 0.17430471683617624
Training model for feature:  logs
F1 score: 0.14285795937913512
Training model for feature:  logs
F1 score: 0.16321311334130664
Training model for feature:  logs
F1 score: 0.18431736325676976
Training model for feature:  logs
F1 score: 0.1938633743030063
Training model for feature:  logs
F1 score: 0.18791964694097285
Training model for feature:  logs
F1 score: 0.15098987028066574
Training model for feature:  logs
F1 score: 0.16143279831795954
Training model for feature:  logs
F1 score: 0.16752969978154503
Training model for feature:  logs
F1 score

In [6]:
best_params

{'colsample_bytree': 0.7656135429860518,
 'gamma': 0.22210123019269762,
 'learning_rate': 0.08047373959576883,
 'max_depth': 6.0,
 'n_estimators': 13.0,
 'reg_lambda': 2.3383880017595646,
 'subsample': 0.8965617242269515}

In [7]:
params = {**XGB_SEARCH_SPACE, **best_params, **{'max_depth':6, 'n_estimators':13}}
xgb_predictor = FeaturePredictor(fdset, model_args=params, feature_model_args=fmodel_args)
xgb_predictor.fit(fdset, verbose=True)

imps = list(zip(fdset.wells[0].logs_args['which_logs'], xgb_predictor.model.feature_importances_))
imps.sort(key = lambda p: p[1])
[print(pair) for pair in imps[::-1]]

Training model for feature:  logs
                      precision    recall  f1-score   support

           sandstone       0.51      0.08      0.14       467
clay-prone sandstone       0.20      0.54      0.29       156
      sandy mudstone       0.13      0.31      0.18       143
            mudstone       0.30      0.14      0.19       178

           micro avg       0.21      0.21      0.21       944
           macro avg       0.28      0.27      0.20       944
        weighted avg       0.36      0.21      0.18       944

Total accuracy Score :  0.2055084745762712
Confusion Matrix: 
 [[ 39 189 191  48]
 [  4  85  65   2]
 [ 23  66  45   9]
 [ 10  95  48  25]]
('RDEP', 0.125)
('NEUT', 0.12402724)
('DENS', 0.12013619)
('GR', 0.11527237)
('DTC', 0.11478599)
('RSHAL', 0.1118677)
('PEF', 0.10651751)
('DTS', 0.09581712)
('DTS1', 0.050583657)
('DTS2', 0.027237354)
('SP', 0.008754863)


[None, None, None, None, None, None, None, None, None, None, None]

In [25]:
xgb_predictor.preds_dataframe('204-19-6', logs=fdset.test_wells[0].logs_args['which_logs'], save_csv='preds_204-19-6.csv')

base  confidence        depth   proba_0   proba_1   proba_2  \
0    2208.085920    0.422048  2208.080467  0.060476  0.204947  0.422048   
1    2208.096661    0.432120  2208.091207  0.061919  0.185974  0.432120   
2    2208.107401    0.390059  2208.101947  0.055892  0.167872  0.390059   
3    2208.118141    0.390059  2208.112687  0.055892  0.167872  0.390059   
4    2208.128881    0.390059  2208.123427  0.055892  0.167872  0.390059   
5    2208.139621    0.390059  2208.134167  0.055892  0.167872  0.390059   
6    2208.150361    0.390142  2208.144907  0.055904  0.167695  0.390142   
7    2208.161101    0.395792  2208.155647  0.056713  0.155642  0.395792   
8    2208.171841    0.395792  2208.166387  0.056713  0.155642  0.395792   
9    2208.182581    0.379869  2208.177127  0.054432  0.189610  0.379869   
10   2208.193321    0.394804  2208.187867  0.040649  0.394804  0.283685   
11   2208.204061    0.366669  2208.198607  0.054353  0.366669  0.290937   
12   2208.214801    0.429816  2208.209347  0.063714  0.429816  0.168824   
13   2208.225541    0.414957  2208.220087  0.061511  0.414957  0.197558   
14   2208.236281    0.414957  2208.230827  0.061511  0.414957  0.197558   
15   2208.247021    0.414957  2208.241567  0.061511  0.414957  0.197558   
16   2208.257761    0.414957  2208.252307  0.061511  0.414957  0.197558   
17   2208.268501    0.414957  2208.263047  0.061511  0.414957  0.197558   
18   2208.279241    0.414957  2208.273788  0.061511  0.414957  0.197558   
19   2208.289982    0.414957  2208.284528  0.061511  0.414957  0.197558   
20   2208.300722    0.414957  2208.295268  0.061511  0.414957  0.197558   
21   2208.311462    0.414957  2208.306008  0.061511  0.414957  0.197558   
22   2208.322202    0.452102  2208.316748  0.067017  0.452102  0.215243   
23   2208.332942    0.452102  2208.327488  0.067017  0.452102  0.215243   
24   2208.343682    0.452102  2208.338228  0.067017  0.452102  0.215243   
25   2208.354422    0.452102  2208.348968  0.067017  0.452102  0.215243   
26   2208.365162    0.452102  2208.359708  0.067017  0.452102  0.215243   
27   2208.375902    0.452102  2208.370448  0.067017  0.452102  0.215243   
28   2208.386642    0.452102  2208.381188  0.067017  0.452102  0.215243   
29   2208.397382    0.452102  2208.391928  0.067017  0.452102  0.215243   
..           ...         ...          ...       ...       ...       ...   
914  2220.392012    0.782688  2220.386558  0.027002  0.782688  0.145599   
915  2220.402752    0.782688  2220.397298  0.027002  0.782688  0.145599   
916  2220.413492    0.782688  2220.408038  0.027002  0.782688  0.145599   
917  2220.424232    0.782688  2220.418778  0.027002  0.782688  0.145599   
918  2220.434972    0.782688  2220.429518  0.027002  0.782688  0.145599   
919  2220.445712    0.782688  2220.440258  0.027002  0.782688  0.145599   
920  2220.456452    0.782688  2220.450998  0.027002  0.782688  0.145599   
921  2220.467192    0.766648  2220.461739  0.028995  0.766648  0.156345   
922  2220.477933    0.766648  2220.472479  0.028995  0.766648  0.156345   
923  2220.488673    0.763094  2220.483219  0.033497  0.763094  0.155620   
924  2220.499413    0.781982  2220.493959  0.030826  0.781982  0.143213   
925  2220.510153    0.781982  2220.504699  0.030826  0.781982  0.143213   
926  2220.520893    0.781982  2220.515439  0.030826  0.781982  0.143213   
927  2220.531633    0.781982  2220.526179  0.030826  0.781982  0.143213   
928  2220.542373    0.781982  2220.536919  0.030826  0.781982  0.143213   
929  2220.553113    0.781982  2220.547659  0.030826  0.781982  0.143213   
930  2220.563853    0.781982  2220.558399  0.030826  0.781982  0.143213   
931  2220.574593    0.794369  2220.569139  0.029075  0.794369  0.135076   
932  2220.585333    0.792457  2220.579879  0.031411  0.792457  0.134751   
933  2220.596073    0.790412  2220.590619  0.033911  0.790412  0.134404   
934  2220.606813    0.793203  2220.601359  0.042304  0.793203  0.134878   
935  2220.617553    0.792560  2220.61