In [1]:
import gc

import numpy as np
import pandas as pd
from random import sample

import hyperopt
from hyperopt import hp, Trials
from hyperopt.pyll.base import scope

from sklearn.metrics import f1_score, log_loss, accuracy_score
from sklearn.utils.class_weight import compute_sample_weight

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

from coremdlr.models import NetworkModel
from coremdlr.config import defaults

from coremdlr.datasets import WellLoader, FaciesDataset
from coremdlr.datasets.utils import infer_test_wells

import matplotlib.pyplot as plt
%matplotlib inline

/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ross/anaconda3/envs/core-dev/lib/python3

In [2]:
DEEPTEN_ARGS = {
    'feature' : 'image',
    'network' : 'deepten',
    'summary' : True,
    'sequence_size' : 12,
    'network_args' : {
        'backbone_cnn' : 'vgg16',
        'conv1x1' : 40,
        'encode_K' : 24,
        'apply_rowwise' : True,
        'lstm_features' : None,
        'dropout_rate' : 0.5,
    },
    'optimizer_args' : {
        'optimizer' : 'Adam',
        'clipnorm' : 1.0
    }
}

IMAGE_ARGS = {
    'image_width' : 200,
    'crop_method' : 'center',
    'downsample' : 2
}


fit_args = {
    'batch_size' : 4,
    'epochs' : 25,
    'class_weighted' : True
}

CHKPT_FNAME = 'temp_best_weights.h5'

In [3]:
def pred_results_df(num_train, model_config):
    gc.collect()
    
    assert num_train in [3, 6, 9], 'Must use one of predefined train/test splits'
    
    train_sets = getattr(defaults, f'TRAIN_SETS_{num_train}')
    
    pred_dfs = []
    
    for i, train_set in enumerate(train_sets):
        gc.collect()
        
        dset = FaciesDataset(train_set, infer_test_wells(train_set), features=['image'],
                            image_args=IMAGE_ARGS)
        
        dset.load_or_generate_data()
        
        print(np.unique(dset.y_train), np.unique(dset.y_test))
        
        model = NetworkModel(dset, model_args=model_config)
        
        chkpt_callback = ModelCheckpoint(CHKPT_FNAME, monitor='val_acc', verbose=1,
                                        save_best_only=True, 
                                        save_weights_only=True)

        earlystop_callback = EarlyStopping(monitor='val_acc', patience=3)
        
        model.fit(dset, callbacks=[chkpt_callback, earlystop_callback], verbose=False, **fit_args)
        
        model.network.load_weights(CHKPT_FNAME)
        
        #print('predict_proba: ', model.predict_proba(dset.X_test))
        
        for test_well_name in dset.test_well_names:
            df = model.preds_dataframe(test_well_name)
            df['well'] = test_well_name
            df['set_number'] = i
            pred_dfs.append(df)
        
        del dset; del model;
        
    return pd.concat(pred_dfs)

In [4]:
preds_df_9 = pred_results_df(9, DEEPTEN_ARGS)

[b'nc', b'bs', b's', b'is', b'ih', b'os', b'sh']
Loading Well:  204-19-3A  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (9590,)), ('top', (9590,)), ('base', (9590,)), ('image', (9590, 32, 200, 3))]
Loading Well:  204-20-1  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (11210,)), ('top', (11210,)), ('base', (11210,)), ('image', (11210, 32, 200, 3))]
Loading Well:  204-19-7  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (9807,)), ('top', (9807,)), ('base', (9807,)), ('image', (9807, 32, 200, 3))]
Loading Well:  205-21b-3  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (3842,)), ('top', (3842,)), ('base', (3842,)), ('image', (3842, 32, 200, 3))]
Loading Well:  204-20-6a  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (3542,)), ('top', (3542,)), ('base', (3542,)), ('image', (3542, 32, 200, 3))]
Loading Well:  204-20a-7

/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


Loading Well:  204-20-3  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (10906,)), ('top', (10906,)), ('base', (10906,)), ('image', (10906, 32, 200, 3))]
Loading Well:  204-24a-6  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (13006,)), ('top', (13006,)), ('base', (13006,)), ('image', (13006, 32, 200, 3))]
Loading Well:  204-24a-7  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (19294,)), ('top', (19294,)), ('base', (19294,)), ('image', (19294, 32, 200, 3))]


/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


[0 1 2 3 4] [0 1 2 3 4]
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor




Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 384, 200, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 384, 200, 64) 1792        input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, 384, 200, 64) 36928       block1_conv1[0][0]               
_______________________________

Shapes of `(batch_X, batch_y)`: (4, 384, 200, 3), (4, 12, 5)
Epoch 1/25
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
1991/1992 [============================>.] - ETA: 0s - loss: 1.0684 - acc: 0.4594
Epoch 00001: val_acc improved from -inf to 0.50981, saving model to temp_best_weights.h5
1992/1992 [==============================] - 210s 105ms/step - loss: 1.0685 - acc: 0.4592 - val_loss: 1.1151 - val_acc: 0.5098
Epoch 2/25
1991/1992 [============================>.] - ETA: 0s - loss: 0.9806 - acc: 0.5254
Epoch 00002: val_acc did not improve from 0.50981
1992/1992 [==============================] - 201s 101ms/step - loss: 0.9802 - acc: 0.5256 - val_loss: 1.1865 - val_acc: 0.3472
Epoch 3/25
1991/1992 [============================>.] - ETA: 0s - loss: 0.8933 - acc: 0.6018
Epoch 00003: val_acc did not improve from 0.50981
1992/1992 [==============================] - 201s 101ms/step - loss: 0.8932 - acc: 0.6019 - val_loss: 1.1514 - val_acc: 0.2

/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


Loading Well:  204-20-3  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (10906,)), ('top', (10906,)), ('base', (10906,)), ('image', (10906, 32, 200, 3))]
Loading Well:  204-20-1  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (11210,)), ('top', (11210,)), ('base', (11210,)), ('image', (11210, 32, 200, 3))]
Loading Well:  204-19-6  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (1947,)), ('top', (1947,)), ('base', (1947,)), ('image', (1947, 32, 200, 3))]


/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


[0 1 2 3 4] [0 1 2 3 4]
Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 384, 200, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 384, 200, 64) 1792        input_2[0][0]                    
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, 384, 200, 64) 36928       block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_pool (MaxPooling2D)      (None, 192, 100, 64) 0           block1_conv2[0][0]               
____________________________________________________________________

Epoch 2/25
2788/2789 [============================>.] - ETA: 0s - loss: 0.9848 - acc: 0.5116
Epoch 00002: val_acc improved from 0.13966 to 0.31912, saving model to temp_best_weights.h5
2789/2789 [==============================] - 246s 88ms/step - loss: 0.9851 - acc: 0.5115 - val_loss: 1.1495 - val_acc: 0.3191
Epoch 3/25
2788/2789 [============================>.] - ETA: 0s - loss: 0.9384 - acc: 0.5446
Epoch 00003: val_acc improved from 0.31912 to 0.48583, saving model to temp_best_weights.h5
2789/2789 [==============================] - 246s 88ms/step - loss: 0.9383 - acc: 0.5447 - val_loss: 0.9984 - val_acc: 0.4858
Epoch 4/25
2788/2789 [============================>.] - ETA: 0s - loss: 0.9251 - acc: 0.5617
Epoch 00004: val_acc did not improve from 0.48583
2789/2789 [==============================] - 245s 88ms/step - loss: 0.9249 - acc: 0.5619 - val_loss: 7.6696e-06 - val_acc: 0.2604
Epoch 5/25
2788/2789 [============================>.] - ETA: 0s - loss: 0.8694 - acc: 0.6088
Epoch 00005:

/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


Loading Well:  205-21b-3  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (3842,)), ('top', (3842,)), ('base', (3842,)), ('image', (3842, 32, 200, 3))]
Loading Well:  204-19-3A  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (9590,)), ('top', (9590,)), ('base', (9590,)), ('image', (9590, 32, 200, 3))]
Loading Well:  204-19-7  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (9807,)), ('top', (9807,)), ('base', (9807,)), ('image', (9807, 32, 200, 3))]


/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


[0 1 2 3 4] [0 1 2 3 4]
Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 384, 200, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 384, 200, 64) 1792        input_3[0][0]                    
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, 384, 200, 64) 36928       block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_pool (MaxPooling2D)      (None, 192, 100, 64) 0           block1_conv2[0][0]               
____________________________________________________________________

Epoch 2/25
2823/2824 [============================>.] - ETA: 0s - loss: 1.0604 - acc: 0.4758
Epoch 00002: val_acc did not improve from 0.40837
2824/2824 [==============================] - 249s 88ms/step - loss: 1.0606 - acc: 0.4756 - val_loss: 7.7669e-06 - val_acc: 0.2837
Epoch 3/25
2823/2824 [============================>.] - ETA: 0s - loss: 1.0806 - acc: 0.4703
Epoch 00003: val_acc did not improve from 0.40837
2824/2824 [==============================] - 249s 88ms/step - loss: 1.0806 - acc: 0.4702 - val_loss: 7.7669e-06 - val_acc: 0.2837
Epoch 4/25
2823/2824 [============================>.] - ETA: 0s - loss: 0.9956 - acc: 0.5644
Epoch 00004: val_acc did not improve from 0.40837
2824/2824 [==============================] - 249s 88ms/step - loss: 0.9954 - acc: 0.5645 - val_loss: 7.7669e-06 - val_acc: 0.2837
[b'nc', b'bs', b's', b'is', b'ih', b'os', b'sh']
Loading Well:  204-19-7  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (9807,)), ('top', (9807,))

/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


Loading Well:  204-20-3  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (10906,)), ('top', (10906,)), ('base', (10906,)), ('image', (10906, 32, 200, 3))]
Loading Well:  204-24a-6  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (13006,)), ('top', (13006,)), ('base', (13006,)), ('image', (13006, 32, 200, 3))]
Loading Well:  204-20-1Z  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (1917,)), ('top', (1917,)), ('base', (1917,)), ('image', (1917, 32, 200, 3))]


/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


[0 1 2 3 4] [0 1 2 3 4]
Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 384, 200, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 384, 200, 64) 1792        input_4[0][0]                    
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, 384, 200, 64) 36928       block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_pool (MaxPooling2D)      (None, 192, 100, 64) 0           block1_conv2[0][0]               
____________________________________________________________________

Epoch 2/25
2715/2716 [============================>.] - ETA: 0s - loss: 0.9082 - acc: 0.5974
Epoch 00002: val_acc improved from 0.26365 to 0.46571, saving model to temp_best_weights.h5
2716/2716 [==============================] - 244s 90ms/step - loss: 0.9081 - acc: 0.5974 - val_loss: 1.1265 - val_acc: 0.4657
Epoch 3/25
2715/2716 [============================>.] - ETA: 0s - loss: 0.8840 - acc: 0.6085
Epoch 00003: val_acc improved from 0.46571 to 0.53584, saving model to temp_best_weights.h5
2716/2716 [==============================] - 245s 90ms/step - loss: 0.8844 - acc: 0.6082 - val_loss: 1.1013 - val_acc: 0.5358
Epoch 4/25
2715/2716 [============================>.] - ETA: 0s - loss: 0.8687 - acc: 0.6174
Epoch 00004: val_acc did not improve from 0.53584
2716/2716 [==============================] - 244s 90ms/step - loss: 0.8684 - acc: 0.6175 - val_loss: 7.9439e-06 - val_acc: 0.3918
Epoch 5/25
2715/2716 [============================>.] - ETA: 0s - loss: 0.8988 - acc: 0.6015
Epoch 00005:

/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


Loading Well:  204-19-3A  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (9590,)), ('top', (9590,)), ('base', (9590,)), ('image', (9590, 32, 200, 3))]
Loading Well:  204-20a-7  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (3105,)), ('top', (3105,)), ('base', (3105,)), ('image', (3105, 32, 200, 3))]
Loading Well:  204-20-1  from  /home/ross/Dropbox/core_data/facies/train_data
Feature shapes:  [('depth', (11210,)), ('top', (11210,)), ('base', (11210,)), ('image', (11210, 32, 200, 3))]


/home/ross/anaconda3/envs/core-dev/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


[0 1 2 3 4] [0 1 2 3 4]
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            [(None, 384, 200, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 384, 200, 64) 1792        input_5[0][0]                    
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, 384, 200, 64) 36928       block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_pool (MaxPooling2D)      (None, 192, 100, 64) 0           block1_conv2[0][0]               
____________________________________________________________________

Epoch 2/25
2795/2796 [============================>.] - ETA: 0s - loss: 1.0025 - acc: 0.5389
Epoch 00002: val_acc improved from 0.30573 to 0.52450, saving model to temp_best_weights.h5
2796/2796 [==============================] - 248s 89ms/step - loss: 1.0027 - acc: 0.5387 - val_loss: 1.0980 - val_acc: 0.5245
Epoch 3/25
2795/2796 [============================>.] - ETA: 0s - loss: 0.9634 - acc: 0.5546
Epoch 00003: val_acc did not improve from 0.52450
2796/2796 [==============================] - 248s 89ms/step - loss: 0.9634 - acc: 0.5546 - val_loss: 1.2638 - val_acc: 0.0755
Epoch 4/25
2795/2796 [============================>.] - ETA: 0s - loss: 0.9645 - acc: 0.5568
Epoch 00004: val_acc did not improve from 0.52450
2796/2796 [==============================] - 248s 89ms/step - loss: 0.9642 - acc: 0.5569 - val_loss: 1.0932 - val_acc: 0.2949
Epoch 5/25
2795/2796 [============================>.] - ETA: 0s - loss: 0.9582 - acc: 0.5632
Epoch 00005: val_acc did not improve from 0.52450
2796/279

In [5]:
from pathlib import Path

results_dir = Path('/home/ross/Dropbox/core_data/model_results/')

preds_df_9.to_csv(str(results_dir / 'image_deepten_results_train_sets9_FINAL.csv'))

In [6]:
accuracy_score(preds_df_9.y_pred.values, preds_df_9.y_true.values)

0.4699506322145107