In [1]:
import lasio
import pandas as pd
import numpy as np

In [2]:
logs_file = '/home/administrator/Dropbox/core_data/facies/train_data/204-19-6_logs.las'
logs_df = lasio.read(logs_file).df()

Header section Parameter regexp=~P was not found.


In [4]:
logs_df.columns

Index(['CALI', 'DENC', 'DENS', 'DTC', 'DTS1', 'DTS2', 'GR', 'NEUT', 'PEF',
       'RDEP', 'RMIC', 'RSHAL', 'SP'],
      dtype='object')

In [9]:
logs_df.isna().count(), logs_df.index.size

(CALI     15092
 DENC     15092
 DENS     15092
 DTC      15092
 DTS1     15092
 DTS2     15092
 GR       15092
 NEUT     15092
 PEF      15092
 RDEP     15092
 RMIC     15092
 RSHAL    15092
 SP       15092
 dtype: int64, 15092)

In [10]:
logs_file = '/home/administrator/Dropbox/core_data/facies/train_data/204-20-6a_logs.las'
logs_df = lasio.read(logs_file).df()
logs_df.columns

Header section Parameter regexp=~P was not found.


Index(['AT60', 'CALI', 'DENC', 'DENS', 'DTC', 'DTS', 'GR', 'NEUT', 'PEF',
       'RDEP', 'RMED', 'RSHAL'],
      dtype='object')

In [11]:
logs_df.isna().count(), logs_df.index.size

(AT60     14751
 CALI     14751
 DENC     14751
 DENS     14751
 DTC      14751
 DTS      14751
 GR       14751
 NEUT     14751
 PEF      14751
 RDEP     14751
 RMED     14751
 RSHAL    14751
 dtype: int64, 14751)

In [13]:
lf = lasio.read(logs_file)

Header section Parameter regexp=~P was not found.


In [14]:
dir(lf)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_text',
 'add_curve',
 'add_curve_raw',
 'append_curve',
 'append_curve_item',
 'curves',
 'curvesdict',
 'data',
 'delete_curve',
 'depth_ft',
 'depth_m',
 'df',
 'encoding',
 'get_curve',
 'header',
 'index',
 'index_unit',
 'insert_curve',
 'insert_curve_item',
 'items',
 'iteritems',
 'iterkeys',
 'itervalues',
 'json',
 'keys',
 'match_raw_section',
 'metadata',
 'other',
 'params',
 'raw_sections',
 'read',
 'sections',
 'set_data',
 'set_data_from_df',
 'to_csv',
 'to_excel',
 'values',
 'version',
 'well',
 'write']

In [16]:
lf.values()

[array([ 457.    ,  457.1524,  457.3048, ..., 2704.5952, 2704.7476,
        2704.9   ]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan])]

In [21]:
logs_df = lf.df()

In [35]:
cond = (2175 <= logs_df.index)
cond2 = (logs_df.index <= 2200)
logs_df[cond & cond2]

AT60     CALI    DENC    DENS       DTC       DTS       GR  \
DEPTH                                                                      
2175.0052  44.6350  12.7316  0.0026  2.1735   98.2955  195.1262  34.4035   
2175.1576  37.7605  12.6997 -0.0127  2.1739   97.6885  188.3434  30.3090   
2175.3100  36.9033  12.7701 -0.0111  2.1990   96.3291  192.2567  31.3312   
2175.4624  53.8636  12.6457 -0.0117  2.2104   95.7009  189.5175  30.5660   
2175.6148  35.2632  12.5915 -0.0146  2.2216   95.5966  189.0858  31.3243   
2175.7672  22.6363  12.4770 -0.0141  2.2315   95.5400  180.8995  32.4482   
2175.9196  13.9423  12.4151 -0.0116  2.2577   94.3143  180.2883  36.0550   
2176.0720  11.3222  12.4114 -0.0146  2.2954   96.1936  176.1380  38.4423   
2176.2244   5.8073  12.4059 -0.0130  2.3486   96.7802  177.9785  47.8227   
2176.3768   4.5817  12.4574 -0.0124  2.3571   97.4163  188.6359  48.3556   
2176.5292   3.9982  12.3645 -0.0125  2.3347   99.4411  188.0279  47.2943   
2176.6816   3.7840  12.1782 -0.0140  2.3359  100.5260  194.2289  52.9932   
2176.8340   3.3357  12.1982 -0.0074  2.3859  101.2734  200.1261  62.6910   
2176.9864   3.3503  12.2208 -0.0039  2.4333  100.8906  202.3542  66.9476   
2177.1388   3.3326  12.2184 -0.0010  2.4417   99.6627  203.7725  66.6726   
2177.2912   3.3169  12.2186 -0.0040  2.4263   98.8205  203.2178  69.2372   
2177.4436   3.2354  12.2533 -0.0048  2.4173   99.4335  205.8463  67.3016   
2177.5960   3.2218  12.2686 -0.0036  2.4134  100.5262  206.4993  68.2804   
2177.7484   3.2055  12.2956 -0.0025  2.4126  102.4734  206.4366  69.5383   
2177.9008   3.2238  12.3168 -0.0060  2.4065  103.1807  201.9595  68.3173   
2178.0532   3.2414  12.2785 -0.0061  2.4059  102.8828  198.8273  66.3947   
2178.2056   3.4707  12.2343 -0.0049  2.3983  101.4396  195.4777  68.9159   
2178.3580   3.4436  12.2421 -0.0057  2.3928  101.7626  194.6973  69.6463   
2178.5104   3.3688  12.2491 -0.0063  2.3916  101.0544  196.8470  71.3770   
2178.6628   3.3348  12.2121 -0.0042  2.4042   99.7202  192.4614  69.4486   
2178.8152   3.3749  12.2237 -0.0025  2.4194   97.2438  190.8732  68.5943   
2178.9676   3.5595  12.2359 -0.0028  2.4319   95.5190  192.9907  68.6079   
2179.1200   3.7889  12.2423 -0.0013  2.4416   95.1657  193.5851  67.9600   
2179.2724   3.9239  12.2163  0.0007  2.4389   94.1874  194.6447  69.1707   
2179.4248   6.8642  12.2309 -0.0031  2.3774   94.3438  194.3526  67.6349   
...            ...      ...     ...     ...       ...       ...      ...   
2195.5792   2.4452  12.0649 -0.0002  2.4239  103.3347  212.8777  66.8239   
2195.7316   2.4152  12.1025 -0.0028  2.4192  103.2074  212.4862  71.3246   
2195.8840   2.4005  12.1150 -0.0038  2.4278  102.9536  214.7177  72.5512   
2196.0364   2.2872  12.1497 -0.0049  2.4350  102.7212  216.1766  77.0447   
2196.1888   2.2769  12.2072 -0.0045  2.4461  103.3561  218.3765  82.5393   
2196.3412   2.2868  12.2359 -0.0021  2.4583  102.7801  219.0475  79.1674   
2196.4936   2.2891  12.2917 -0.0037  2.4541  102.0829  217.4514  82.3206   
2196.6460   2.2339  12.2658 -0.0031  2.4494  102.6275  208.9717  73.7450   
2196.7984   2.3993  12.2460 -0.0028  2.4397  102.2656  201.1904  71.2181   
2196.9508   2.6989  12.2066  0.0005  2.4209  101.1130  190.6472  69.3621   
2197.1032   2.8674  12.1944 -0.0024  2.3943   98.7607  177.6843  67.1060   
2197.2556   3.7301  12.1939 -0.0025  2.3930   83.0170  157.0083  46.9552   
2197.4080   4.3170  12.1621 -0.0010  2.4369   75.5611  141.4562  42.4082   
2197.5604   5.1735  12.1103  0.0012  2.5027   69.8392  133.2077  36.2199   
2197.7128   5.1804  12.1129 -0.0025  2.5526   67.7227  131.7592  32.2628   
2197.8652   5.0014  12.1676 -0.0001  2.5899   65.3332  129.3927  31.8820   
2198.0176   3.0293  12.2075  0.0002  2.6030   72.2576  135.3155  32.4186   
2198.1700   2.5539  12.1857 -0.0018  2.5419   81.4637  146.6457  38.6401   
2198.3224   2.3384  12.1950 -0.0069  2.4269   87.9413  159.2642  38.3766   
2198.4748   2.2525  12.2008 -0.0103  2.3321   91.9368  164.890

In [36]:
logs_df["TEST_NAN"] = np.nan
logs_df

AT60  CALI  DENC  DENS  DTC  DTS       GR  NEUT  PEF  RDEP  RMED  \
DEPTH                                                                         
457.0000    NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
457.1524    NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
457.3048    NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
457.4572    NaN   NaN   NaN   NaN  NaN  NaN  10.8312   NaN  NaN   NaN   NaN   
457.6096    NaN   NaN   NaN   NaN  NaN  NaN   9.4180   NaN  NaN   NaN   NaN   
457.7620    NaN   NaN   NaN   NaN  NaN  NaN   9.0442   NaN  NaN   NaN   NaN   
457.9144    NaN   NaN   NaN   NaN  NaN  NaN  10.4243   NaN  NaN   NaN   NaN   
458.0668    NaN   NaN   NaN   NaN  NaN  NaN   9.6658   NaN  NaN   NaN   NaN   
458.2192    NaN   NaN   NaN   NaN  NaN  NaN  10.1648   NaN  NaN   NaN   NaN   
458.3716    NaN   NaN   NaN   NaN  NaN  NaN  10.1072   NaN  NaN   NaN   NaN   
458.5240    NaN   NaN   NaN   NaN  NaN  NaN   9.4851   NaN  NaN   NaN   NaN   
458.6764    NaN   NaN   NaN   NaN  NaN  NaN  10.7146   NaN  NaN   NaN   NaN   
458.8288    NaN   NaN   NaN   NaN  NaN  NaN   9.5249   NaN  NaN   NaN   NaN   
458.9812    NaN   NaN   NaN   NaN  NaN  NaN  10.4012   NaN  NaN   NaN   NaN   
459.1336    NaN   NaN   NaN   NaN  NaN  NaN  11.4514   NaN  NaN   NaN   NaN   
459.2860    NaN   NaN   NaN   NaN  NaN  NaN  10.9498   NaN  NaN   NaN   NaN   
459.4384    NaN   NaN   NaN   NaN  NaN  NaN   9.9839   NaN  NaN   NaN   NaN   
459.5908    NaN   NaN   NaN   NaN  NaN  NaN   9.1138   NaN  NaN   NaN   NaN   
459.7432    NaN   NaN   NaN   NaN  NaN  NaN   9.7806   NaN  NaN   NaN   NaN   
459.8956    NaN   NaN   NaN   NaN  NaN  NaN   9.7912   NaN  NaN   NaN   NaN   
460.0480    NaN   NaN   NaN   NaN  NaN  NaN  10.8133   NaN  NaN   NaN   NaN   
460.2004    NaN   NaN   NaN   NaN  NaN  NaN   9.3317   NaN  NaN   NaN   NaN   
460.3528    NaN   NaN   NaN   NaN  NaN  NaN   8.7446   NaN  NaN   NaN   NaN   
460.5052    NaN   NaN   NaN   NaN  NaN  NaN   9.5514   NaN  NaN   NaN   NaN   
460.6576    NaN   NaN   NaN   NaN  NaN  NaN   9.9542   NaN  NaN   NaN   NaN   
460.8100    NaN   NaN   NaN   NaN  NaN  NaN   8.4413   NaN  NaN   NaN   NaN   
460.9624    NaN   NaN   NaN   NaN  NaN  NaN  11.2823   NaN  NaN   NaN   NaN   
461.1148    NaN   NaN   NaN   NaN  NaN  NaN  11.7365   NaN  NaN   NaN   NaN   
461.2672    NaN   NaN   NaN   NaN  NaN  NaN   9.7969   NaN  NaN   NaN   NaN   
461.4196    NaN   NaN   NaN   NaN  NaN  NaN  11.0403   NaN  NaN   NaN   NaN   
...         ...   ...   ...   ...  ...  ...      ...   ...  ...   ...   ...   
2700.4804   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2700.6328   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2700.7852   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2700.9376   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.0900   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.2424   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.3948   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.5472   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.6996   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.8520   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.0044   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.1568   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.3092   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.4616   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.6140   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.7664   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.9188   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2703.0712   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  N

In [37]:
logs_df

AT60  CALI  DENC  DENS  DTC  DTS       GR  NEUT  PEF  RDEP  RMED  \
DEPTH                                                                         
457.0000    NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
457.1524    NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
457.3048    NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
457.4572    NaN   NaN   NaN   NaN  NaN  NaN  10.8312   NaN  NaN   NaN   NaN   
457.6096    NaN   NaN   NaN   NaN  NaN  NaN   9.4180   NaN  NaN   NaN   NaN   
457.7620    NaN   NaN   NaN   NaN  NaN  NaN   9.0442   NaN  NaN   NaN   NaN   
457.9144    NaN   NaN   NaN   NaN  NaN  NaN  10.4243   NaN  NaN   NaN   NaN   
458.0668    NaN   NaN   NaN   NaN  NaN  NaN   9.6658   NaN  NaN   NaN   NaN   
458.2192    NaN   NaN   NaN   NaN  NaN  NaN  10.1648   NaN  NaN   NaN   NaN   
458.3716    NaN   NaN   NaN   NaN  NaN  NaN  10.1072   NaN  NaN   NaN   NaN   
458.5240    NaN   NaN   NaN   NaN  NaN  NaN   9.4851   NaN  NaN   NaN   NaN   
458.6764    NaN   NaN   NaN   NaN  NaN  NaN  10.7146   NaN  NaN   NaN   NaN   
458.8288    NaN   NaN   NaN   NaN  NaN  NaN   9.5249   NaN  NaN   NaN   NaN   
458.9812    NaN   NaN   NaN   NaN  NaN  NaN  10.4012   NaN  NaN   NaN   NaN   
459.1336    NaN   NaN   NaN   NaN  NaN  NaN  11.4514   NaN  NaN   NaN   NaN   
459.2860    NaN   NaN   NaN   NaN  NaN  NaN  10.9498   NaN  NaN   NaN   NaN   
459.4384    NaN   NaN   NaN   NaN  NaN  NaN   9.9839   NaN  NaN   NaN   NaN   
459.5908    NaN   NaN   NaN   NaN  NaN  NaN   9.1138   NaN  NaN   NaN   NaN   
459.7432    NaN   NaN   NaN   NaN  NaN  NaN   9.7806   NaN  NaN   NaN   NaN   
459.8956    NaN   NaN   NaN   NaN  NaN  NaN   9.7912   NaN  NaN   NaN   NaN   
460.0480    NaN   NaN   NaN   NaN  NaN  NaN  10.8133   NaN  NaN   NaN   NaN   
460.2004    NaN   NaN   NaN   NaN  NaN  NaN   9.3317   NaN  NaN   NaN   NaN   
460.3528    NaN   NaN   NaN   NaN  NaN  NaN   8.7446   NaN  NaN   NaN   NaN   
460.5052    NaN   NaN   NaN   NaN  NaN  NaN   9.5514   NaN  NaN   NaN   NaN   
460.6576    NaN   NaN   NaN   NaN  NaN  NaN   9.9542   NaN  NaN   NaN   NaN   
460.8100    NaN   NaN   NaN   NaN  NaN  NaN   8.4413   NaN  NaN   NaN   NaN   
460.9624    NaN   NaN   NaN   NaN  NaN  NaN  11.2823   NaN  NaN   NaN   NaN   
461.1148    NaN   NaN   NaN   NaN  NaN  NaN  11.7365   NaN  NaN   NaN   NaN   
461.2672    NaN   NaN   NaN   NaN  NaN  NaN   9.7969   NaN  NaN   NaN   NaN   
461.4196    NaN   NaN   NaN   NaN  NaN  NaN  11.0403   NaN  NaN   NaN   NaN   
...         ...   ...   ...   ...  ...  ...      ...   ...  ...   ...   ...   
2700.4804   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2700.6328   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2700.7852   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2700.9376   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.0900   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.2424   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.3948   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.5472   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.6996   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2701.8520   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.0044   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.1568   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.3092   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.4616   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.6140   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.7664   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2702.9188   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN   
2703.0712   NaN   NaN   NaN   NaN  NaN  NaN      NaN   NaN  N

array([ True,  True,  True, ...,  True,  True,  True])