In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [4]:
from tensorflow.keras.utils import to_categorical

In [5]:
import numpy as np

In [14]:
y_true = to_categorical(np.random.randint(0, 4, (10,)))
y_pred = np.random.rand(10, 4)
y_pred /= y_pred.sum(axis=1)[:, np.newaxis]
y_true, y_pred

(array([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]], dtype=float32),
 array([[0.62755244, 0.10050523, 0.16103299, 0.11090934],
        [0.28469981, 0.26675584, 0.27346896, 0.17507539],
        [0.38709757, 0.26730841, 0.25855619, 0.08703782],
        [0.13888813, 0.31060692, 0.19750349, 0.35300146],
        [0.06063935, 0.027504  , 0.61010513, 0.30175152],
        [0.06929531, 0.40179132, 0.4509782 , 0.07793516],
        [0.3342041 , 0.21003941, 0.00077661, 0.45497988],
        [0.25820292, 0.27029301, 0.19656849, 0.27493557],
        [0.45861507, 0.01450553, 0.28536225, 0.24151715],
        [0.20263174, 0.61210056, 0.07913651, 0.1061312 ]]))

In [15]:
y_pred = tf.convert_to_tensor(y_pred)
y_true = tf.convert_to_tensor(y_true, preferred_dtype=y_pred.dtype)

In [16]:
y_pred

<tf.Tensor: id=1, shape=(10, 4), dtype=float64, numpy=
array([[0.62755244, 0.10050523, 0.16103299, 0.11090934],
       [0.28469981, 0.26675584, 0.27346896, 0.17507539],
       [0.38709757, 0.26730841, 0.25855619, 0.08703782],
       [0.13888813, 0.31060692, 0.19750349, 0.35300146],
       [0.06063935, 0.027504  , 0.61010513, 0.30175152],
       [0.06929531, 0.40179132, 0.4509782 , 0.07793516],
       [0.3342041 , 0.21003941, 0.00077661, 0.45497988],
       [0.25820292, 0.27029301, 0.19656849, 0.27493557],
       [0.45861507, 0.01450553, 0.28536225, 0.24151715],
       [0.20263174, 0.61210056, 0.07913651, 0.1061312 ]])>

In [17]:
y_true

<tf.Tensor: id=2, shape=(10, 4), dtype=float64, numpy=
array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])>

In [22]:
a = tf.expand_dims(tf.range(0, 4, dtype=y_pred.dtype), axis=-1)
a

<tf.Tensor: id=23, shape=(4, 1), dtype=float64, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]])>

In [36]:
tf.matmul(y_pred, a)

<tf.Tensor: id=55, shape=(10, 1), dtype=float64, numpy=
array([[0.75529924],
       [1.33891992],
       [1.04553428],
       [1.76461828],
       [2.15296882],
       [1.53755322],
       [1.57653227],
       [1.48823671],
       [1.30978147],
       [1.08876716]])>

In [38]:
y_pred_batches = tf.expand_dims(y_pred, 0)
tf.tensordot(y_pred_batches, a, [[-1], [0]])

<tf.Tensor: id=79, shape=(1, 10, 1), dtype=float64, numpy=
array([[[0.75529924],
        [1.33891992],
        [1.04553428],
        [1.76461828],
        [2.15296882],
        [1.53755322],
        [1.57653227],
        [1.48823671],
        [1.30978147],
        [1.08876716]]])>

In [46]:
tf.cast(tf.argmax(y_true,-1), dtype=y_pred.dtype) - tf.squeeze(tf.tensordot(y_pred_batches, a, [[-1], [0]]))

<tf.Tensor: id=166, shape=(10,), dtype=float64, numpy=
array([ 0.24470076, -1.33891992, -0.04553428, -0.76461828,  0.84703118,
        1.46244678, -1.57653227,  1.51176329,  0.69021853, -1.08876716])>

In [47]:
tf.squeeze(tf.tensordot(y_pred_batches, a, [[-1], [0]]))

<tf.Tensor: id=179, shape=(10,), dtype=float64, numpy=
array([0.75529924, 1.33891992, 1.04553428, 1.76461828, 2.15296882,
       1.53755322, 1.57653227, 1.48823671, 1.30978147, 1.08876716])>

In [49]:
tf.cast(tf.argmax(y_true,-1), dtype=y_pred.dtype)

<tf.Tensor: id=183, shape=(10,), dtype=float64, numpy=array([1., 0., 1., 1., 3., 3., 0., 3., 2., 0.])>

In [1]:
import numpy as np

In [5]:
for x in list(zip(np.random.random((10,2,2)), np.random.random((10,3)))):
    print(x)
    print('...')

(array([[0.42363154, 0.25596107],
       [0.60417042, 0.74358632]]), array([0.04582661, 0.96647151, 0.32468085]))
...
(array([[0.18487166, 0.77029397],
       [0.52425414, 0.5221453 ]]), array([0.48389702, 0.87926068, 0.53094016]))
...
(array([[0.86663356, 0.23984437],
       [0.19932583, 0.50749668]]), array([0.67527856, 0.81270776, 0.11644198]))
...
(array([[0.26667678, 0.74787778],
       [0.36208328, 0.87119365]]), array([0.72149197, 0.22584491, 0.02008119]))
...
(array([[0.87443796, 0.39775366],
       [0.14658737, 0.47046675]]), array([0.24332723, 0.98134861, 0.98223679]))
...
(array([[0.78539592, 0.11261416],
       [0.43810662, 0.85734329]]), array([0.12549947, 0.35923268, 0.16638243]))
...
(array([[0.58511394, 0.16728676],
       [0.04032012, 0.49622668]]), array([0.61866221, 0.34943255, 0.55360597]))
...
(array([[0.47983967, 0.95589617],
       [0.42216673, 0.62267   ]]), array([0.8958161 , 0.54126861, 0.7708302 ]))
...
(array([[0.22294988, 0.20604346],
       [0.36465666, 0.

In [8]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model

In [16]:
_input = Input(shape=(256,))
x = Dense(512)(_input)
p = Dense(1024)(x)
encoder = Model(inputs=_input, outputs=p)
encoder.compile(loss='mse', optimizer='SGD')

for layer in encoder.layers:
    layer.trainable = False 
    
d_input = Input(shape=encoder.output_shape)
x = Dense(512)(d_input)
x = Dense(128)(x)
p = Dense(2)(x)
decoder = Model(inputs=d_input, outputs=p)

encoder.summary()
decoder.summary()

full_in = Input(shape=encoder.input_shape)
x = encoder(full_in)
p = decoder(x)
full = Model(inputs=full_in, ouputs=x)
full.compile(loss='categorical_crossentropy', optimizer='SGD')
full.summary()





_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 256)               0         
_________________________________________________________________
dense_25 (Dense)             (None, 512)               131584    
_________________________________________________________________
dense_26 (Dense)             (None, 1024)              525312    
Total params: 1,313,792
Trainable params: 656,896
Non-trainable params: 656,896
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        (None, None, 1024)        0         
_________________________________________________________________
dense_27 (Dense)             (None, None, 512)         524800    
______________________________________________________________

TypeError: _init_subclassed_network() got an unexpected keyword argument 'inputs'